/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Bibliography.MyListModel;
import Bibliography.Typology;
import Bibliography.MyConnection;
import Bibliography.Theme;
import Bibliography.Document;
import javax.swing.*;
import java.sql.*;
import java.util.*;
/**
 *
 * @author gruppo6
 */
public class Consultation extends javax.swing.JFrame {
    private Connection conn;
    private MyConnection myConn;
    private MyListModel listModelDocuments;
    private String themeSelected;
    private String typologySelected;
    private String extensionSelected;
    private String stateSelected;
    private String rateSelected;
    private boolean themeFlag;
    private boolean typologyFlag;
    private boolean extensionFlag;
    private boolean stateFlag;
    private boolean rateFlag;


    /**
     * Creates new form Consultazione
     */
    public Consultation() {
        initComponents();
    }
    
    public Consultation(MyConnection myConn) {
        initComponents();
        try{
            this.myConn = myConn;
            conn = myConn.getConnection();
        }catch(ClassNotFoundException e){
            System.out.println(e.getMessage());
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        searchField = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        boxTheme = new javax.swing.JComboBox<>();
        boxTypology = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        boxExtension = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDocuments = new javax.swing.JList<>();
        modifyButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        boxState = new javax.swing.JComboBox<>();
        showAllButton = new javax.swing.JButton();
        boxVal = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        findButton.setText("Cerca");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Tematica");

        jLabel3.setText("Tipologia");

        boxTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxThemeActionPerformed(evt);
            }
        });

        boxTypology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTypologyActionPerformed(evt);
            }
        });

        jLabel5.setText("Estensioni");

        boxExtension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxExtensionActionPerformed(evt);
            }
        });

        jLabel1.setText("Valutazione");

        jScrollPane3.setViewportView(listDocuments);

        modifyButton.setText("Modifica");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Letti / Non letti");

        boxState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Documenti letti", "Documenti non letti" }));
        boxState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxStateActionPerformed(evt);
            }
        });

        showAllButton.setLabel("Mostra tutti");
        showAllButton.setMaximumSize(new java.awt.Dimension(61, 23));
        showAllButton.setMinimumSize(new java.awt.Dimension(61, 23));
        showAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllButtonActionPerformed(evt);
            }
        });

        boxVal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5" }));
        boxVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxValActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(337, 337, 337))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(boxExtension, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxTypology, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxTheme, 0, 146, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(boxState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxVal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                                .addComponent(jScrollPane3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(showAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(198, 198, 198)
                                .addComponent(modifyButton)))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxTypology, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(boxState, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(boxVal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(modifyButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(showAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        boxTheme.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        try{
            String search = searchField.getText();
            listModelDocuments.setFilterSearchBar(conn, search);
            
            if(themeSelected.compareTo("") != 0)
                listModelDocuments.setFilterTheme(themeSelected);
            if(typologySelected.compareTo("") != 0)
                listModelDocuments.setFilterTheme(themeSelected);
            if(extensionSelected.compareTo("") != 0)
                listModelDocuments.setFilterTheme(extensionSelected);
            if(stateSelected.compareTo("") != 0)
                listModelDocuments.setFilterTheme(stateSelected);
            if(rateSelected.compareTo("") != 0)
                listModelDocuments.setFilterTheme(rateSelected);
            
            listDocuments.setModel(listModelDocuments.getListModel());
            
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }catch(ClassNotFoundException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_findButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try{
            conn.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try{
        themeSelected = "";
        typologySelected = "";
        extensionSelected = "";
        stateSelected = "";
        rateSelected = "";
        themeFlag = false;
        typologyFlag = false;
        extensionFlag = false;
        stateFlag = false;
        rateFlag = false;
        
        
        //TUTTI I DOCUMENTI
        ArrayList<Document> documents = Document.getDocuments(conn);
        listModelDocuments = new MyListModel();        
        for(Document d : documents){
            listModelDocuments.getListModel().addElement(d);
            listDocuments.setModel(listModelDocuments.getListModel());
        }


        //FILTRI TEMATICHE
        ArrayList<Theme> themes = Theme.getAllThemes(conn);
        DefaultComboBoxModel cbModelThemes = new DefaultComboBoxModel();
        cbModelThemes.addElement("");
        for(Theme t : themes){
            cbModelThemes.addElement(t.toString());
            boxTheme.setModel(cbModelThemes);
        }  
            
        //FILTRI TIPOLOGIE
        ArrayList<Typology> typologies = Typology.getAllTypologies(conn);
        DefaultComboBoxModel cbModelTyp = new DefaultComboBoxModel();
        cbModelTyp.addElement("");
        for(Typology t : typologies){
            cbModelTyp.addElement(t.toString());
            boxTypology.setModel(cbModelTyp);
        }
 
        //FILTRI ESTENSIONE
        ArrayList<String> extensions = Document.getAllExtensions(conn);
        DefaultComboBoxModel cbModelExtensions = new DefaultComboBoxModel();
        cbModelExtensions.addElement("");
        for(String s : extensions){
            cbModelExtensions.addElement(s);
            boxExtension.setModel(cbModelExtensions); 
        }

        }catch(SQLException e){
            System.out.println(e.getMessage());
        }catch(NullPointerException e){
            System.out.println(e.getMessage());
        }catch(ClassNotFoundException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        Document document = (Document) listModelDocuments.getListModel().getElementAt(listDocuments.getSelectedIndex());
        try{
            Modify modify = new Modify(document, myConn);
            modify.setVisible(true);
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void boxThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxThemeActionPerformed
        //Theme theme = theme.getName();
        themeSelected =  (String) boxTheme.getSelectedItem();
        try{
            if(themeSelected.compareTo("") == 0){
                themeFlag = false;
                listModelDocuments.removeFilter(conn, "theme", themeSelected, typologySelected, 
                                                extensionSelected, stateSelected, rateSelected);
                listDocuments.setModel(listModelDocuments.getListModel());
            }else{
                if(themeFlag){
                    listModelDocuments.removeFilter(conn, "theme", "", typologySelected, 
                                                    extensionSelected, stateSelected, rateSelected);
                }
                listModelDocuments.setFilterTheme(themeSelected);
                listDocuments.setModel(listModelDocuments.getListModel());
                themeFlag = true;
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }catch(ClassNotFoundException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_boxThemeActionPerformed

    private void boxTypologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTypologyActionPerformed
        //Typology typology = typology.getName();
        typologySelected =  (String) boxTypology.getSelectedItem();
        try{
            if(typologySelected.compareTo("") == 0){
                typologyFlag = false;
                listModelDocuments.removeFilter(conn, "typology", themeSelected, typologySelected, 
                                                extensionSelected, stateSelected, rateSelected);
                listDocuments.setModel(listModelDocuments.getListModel());
            }else{
                if(typologyFlag){
                    listModelDocuments.removeFilter(conn, "typology", themeSelected, "", 
                                                    extensionSelected, stateSelected, rateSelected);
                }
                listModelDocuments.setFilterTypology(typologySelected);
                listDocuments.setModel(listModelDocuments.getListModel());
                typologyFlag = true;
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }catch(ClassNotFoundException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_boxTypologyActionPerformed

    private void boxExtensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxExtensionActionPerformed
        extensionSelected = (String) boxExtension.getSelectedItem();
        try{
            if(extensionSelected.compareTo("") == 0){
                extensionFlag = false;
                listModelDocuments.removeFilter(conn, "extension", themeSelected, typologySelected, 
                                                extensionSelected, stateSelected, rateSelected);
                listDocuments.setModel(listModelDocuments.getListModel());
            }else{
                if(extensionFlag){
                    listModelDocuments.removeFilter(conn, "extension", themeSelected, typologySelected, 
                                                    "", stateSelected, rateSelected);
                }
                listModelDocuments.setFilterExtension(extensionSelected);
                listDocuments.setModel(listModelDocuments.getListModel());
                extensionFlag = true;
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }catch(ClassNotFoundException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_boxExtensionActionPerformed

    private void boxStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxStateActionPerformed
        stateSelected = (String) boxState.getSelectedItem();
        try{
            if(stateSelected.compareTo("") == 0){
                stateFlag = false;
                listModelDocuments.removeFilter(conn, "state", themeSelected, typologySelected, 
                                                extensionSelected, stateSelected, rateSelected);
                listDocuments.setModel(listModelDocuments.getListModel());
            }else{
                if(stateFlag){
                    listModelDocuments.removeFilter(conn, "state", themeSelected, typologySelected, 
                                                    extensionSelected, "", rateSelected);
                }
                listModelDocuments.setFilterState(stateSelected);
                listDocuments.setModel(listModelDocuments.getListModel());
                stateFlag = true;
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }catch(ClassNotFoundException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_boxStateActionPerformed

    private void showAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllButtonActionPerformed
       try{
        ArrayList<Document> documents = Document.getDocuments(conn);
        listModelDocuments = new MyListModel();        
        for(Document d : documents){
            listModelDocuments.getListModel().addElement(d);
            listDocuments.setModel(listModelDocuments.getListModel());
        }
        
        //DISATTIVARE TUTTI I FILTRI
        
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }catch(ClassNotFoundException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_showAllButtonActionPerformed

    private void boxValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxValActionPerformed
        rateSelected = (String) boxVal.getSelectedItem();
        try{
            if(rateSelected.compareTo("") == 0){
                rateFlag = false;
                listModelDocuments.removeFilter(conn, "rate", themeSelected, typologySelected, 
                                                extensionSelected, stateSelected, rateSelected);
                listDocuments.setModel(listModelDocuments.getListModel());
            }else{
                if(rateFlag){
                    listModelDocuments.removeFilter(conn, "extension", themeSelected, typologySelected, 
                                                    extensionSelected, stateSelected, "");
                }
                listModelDocuments.setFilterRate(rateSelected);
                listDocuments.setModel(listModelDocuments.getListModel());
                rateFlag = true;
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }catch(ClassNotFoundException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_boxValActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxExtension;
    private javax.swing.JComboBox<String> boxState;
    private javax.swing.JComboBox<String> boxTheme;
    private javax.swing.JComboBox<String> boxTypology;
    private javax.swing.JComboBox<String> boxVal;
    private javax.swing.JButton findButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<String> listDocuments;
    private javax.swing.JButton modifyButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton showAllButton;
    // End of variables declaration//GEN-END:variables
}
