/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Bibliography.*;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import javafx.util.converter.LocalDateStringConverter;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;



/**
 *
 * @author Emiliano
 */
public class Modify extends javax.swing.JFrame {
    MyConnection myConnection;
    Connection connection;
    Document document;
    Detail detail;
  
   // ArrayList<PersonalTag> personalTag;
   // ArrayList<KeyWord> keyWord;
    //ArrayList <Comment>comment;
     
     
    /**
     * Creates new form NewJFrame
     */
    public Modify() {
        initComponents();
      
    }

    public Modify(Document document,MyConnection myConnection) throws SQLException{
        initComponents();
        this.myConnection=myConnection;
        this.document=document;
    //    theme= new ArrayList<>();
     //   typology= new ArrayList<>();
      //  comment= new ArrayList<>();
           try {
        connection=myConnection.getConnection();
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }catch(ClassNotFoundException ex){
            System.out.println(ex.getMessage());
        }
      
                   
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        TitleText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AuthorText = new javax.swing.JTextField();
        PersonalTagText = new javax.swing.JTextField();
        KeyWordText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Modifica = new javax.swing.JButton();
        TypologySelect = new javax.swing.JComboBox<>();
        ThemeSelect = new javax.swing.JComboBox<>();
        rateSlider = new javax.swing.JSlider();
        filenameLabel = new javax.swing.JLabel();
        LinkText = new javax.swing.JTextField();
        Link = new javax.swing.JLabel();
        dataReadCalendar = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CommentList = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Titolo");

        jLabel2.setText("Autori");

        jLabel3.setText("Tipologia");

        jLabel4.setText("Tematica");

        jLabel5.setText("Tag");

        jLabel6.setText("Parole Chiave");

        jLabel7.setText("Commenti");

        jLabel8.setText("Valutazione");

        Modifica.setText("Conferma Modifiche");
        Modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaActionPerformed(evt);
            }
        });

        TypologySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypologySelectActionPerformed(evt);
            }
        });

        ThemeSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemeSelectActionPerformed(evt);
            }
        });

        rateSlider.setMajorTickSpacing(1);
        rateSlider.setMaximum(5);
        rateSlider.setMinimum(1);
        rateSlider.setPaintLabels(true);
        rateSlider.setValue(3);

        filenameLabel.setText("nomefile");

        Link.setText("Link");

        jLabel9.setText("Data Lettura");

        jLabel10.setText("Nome File");

        jLabel12.setText("Stato");

        stateLabel.setText("Stato");

        jScrollPane2.setViewportView(CommentList);

        jButton3.setText("Edit Type");

        jButton5.setText("Edit Theme");

        jButton9.setText("Edit Comment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9))
                                            .addGap(36, 36, 36))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Link)
                                                .addComponent(jLabel7)))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(TypologySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(rateSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dataReadCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LinkText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(KeyWordText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PersonalTagText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AuthorText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel12))
                                    .addGap(97, 97, 97)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                        .addComponent(filenameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(stateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ThemeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(Modifica)))
                .addGap(67, 211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(filenameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLabel)
                    .addComponent(jLabel12))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ThemeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AuthorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TypologySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PersonalTagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KeyWordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LinkText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Link))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rateSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dataReadCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(47, 47, 47)
                .addComponent(Modifica)
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypologySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypologySelectActionPerformed

          
    }//GEN-LAST:event_TypologySelectActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
/*
        DefaultComboBoxModel themeModel= new DefaultComboBoxModel();
        DefaultComboBoxModel typeModel= new DefaultComboBoxModel();
        DefaultListModel listModel2= new DefaultListModel();
        
        String str=document.getFileName()+"."+document.getExtension();
          if(document.getState()){
              stateLabel.setText("LETTO");
              dataReadCalendar.setDate(document.getReadDate());
          }else{
              stateLabel.setText("NON LETTO");
          }

        filenameLabel.setText(str);
       
if(document.getRate()!=null){
rateSlider.setValue(document.getRate().getValue());
}
            
if(document.getComments()!=null){       
        for(Comment c: document.getComments()){
                listModel2.addElement(c);
            }
        CommentList.setModel(listModel2);
}


if(document.getDetail()!=null)
{
       
          try{
          
          TitleText.setText(document.getDetail().getTitle());
          LinkText.setText(document.getDetail().getLink());
        

          for(Theme theme:  Theme.getAllThemes(connection)){
              themeModel.addElement(theme);
          }
          ThemeSelect.setModel(themeModel);
           ArrayList<Typology> typeDetails = new ArrayList<>();
        
          for(Typology typology: Typology.getAllTypologies(connection)){
              typeModel.addElement(typology);     
          }
          
                    
                      
         
         StringJoiner sj = new StringJoiner(",");  
         for(Author a: .getAuthorsDetail(document.getId(), myConnection)){
                 sj.add(a.getAuthor());  
         }
         AuthorText.setText(sj.toString());
         
         
           StringJoiner sj2 = new StringJoiner(",");  
         for(PersonalTag p: Detail.getPersonalTagDetail(document.getId(), myConnection)){
                 sj.add(p.getPersonalTag());  
         }
         PersonalTagText.setText(sj2.toString());
         
              StringJoiner sj3 = new StringJoiner(",");  
         for(KeyWord k: Detail.getKeyWordDetail(document.getId(), myConnection)){
                 sj.add(k.getKeyWord());  
         }
         PersonalTagText.setText(sj3.toString());

          }catch(SQLException e){
                  System.out.println(e.getMessage());
              }catch(ClassNotFoundException e){
                  System.out.println(e.getMessage());
              }   
         TypologySelect.setModel(typeModel);

        
         ThemeSelect.setSelectedItem(document.getDetail().getTheme());
         TypologySelect.setSelectedItem(document.getDetail().getTypology());
        
       } */
    }//GEN-LAST:event_formWindowOpened

    private void ModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaActionPerformed
      
        
       // try{
        ListModel themeSelected= ThemeSelect.getModel();    
        Theme theme= (Theme)themeSelected.getElementAt(ThemeSelect.getSelectedIndex());
        System.out.println("Tematica selezionata : "+theme.getName());
        
        
        ListModel typologySelected=TypologySelect.getModel();
        Typology typology= (Typology) typologySelected.getElementAt(TypologySelect.getSelectedIndex());
        System.out.println("Tematica tipologia : "+typology.getName());
      
        

         String title= this.TitleText.getText();
         title=title.replaceAll("^\\s+", "");
         
         String link= this.LinkText.getText();
         
        
      //  System.out.println(titolo);
       String author= this.AuthorText.getText();
       
       
       ArrayList<Author> authorArray= new ArrayList<>();
       
            String[] authors = author.split(",");
                for(int i=0; i<authors.length;i++)
                {
                    author=authors[i];
                    author= author.replaceAll("^\\s+", "");
                    author= author.replaceAll("$\\s+", "");
                    authorArray.add(new Author(author));
                }
                
       ArrayList<KeyWord> keyWordArray= new ArrayList<>();
       String keyWord= this.KeyWordText.getText();
       String[] keyWords= keyWord.split(",");
         for(int i=0; i<keyWords.length;i++){
              keyWord=keyWords[i];
              keyWord=keyWord.replaceAll("^\\s+", "");
              keyWord=keyWord.replaceAll("$\\s+", "");  
              keyWordArray.add(new KeyWord(keyWord));  
        }
        
       ArrayList<PersonalTag> personalTagArray= new ArrayList<>();
       String personalTag= this.PersonalTagText.getText();
       String[] personalTags= personalTag.split(",");

        for(int i=0; i<personalTags.length;i++){
           personalTag=personalTags[i];
            personalTag=personalTag.replaceAll("^\\s+", "");
            personalTag=personalTag.replaceAll("$\\s+", "");  
            personalTagArray.add(new PersonalTag(personalTag));
       }
       
       
            Date dateCalendar= dataReadCalendar.getDate();
            
        
            
            boolean state;
            String dateString=dateCalendar.toString();
            if(dateString.compareTo("")==0){
                dateCalendar=null;
                state=false;
            }else{
                state=true;
            }

        
        Integer rate=rateSlider.getValue();
        ArrayList<Comment> comments= new ArrayList<>();
        
        
        Detail detailModify= new Detail(document.getId(),title,link,theme, typology, authorArray, keyWordArray, personalTagArray);        
        //Document documentModify= new Document(document.getId(),document.getFileName(), document.getExtension(), document.getInsertDate(),dateCalendar, state,comments,rate, detailModify);
        

        /*    
      
  
       
        System.out.println(valoreSlider);
        String tematicaUpdate=tem.get(indexTematica).getTematica();
        String tipologiaUpdate=tipologia.get(indexTipologia).getTipologia();
        
       
      
       if(dettPres==true){
            String updateTableSQL = "UPDATE dettaglio SET link = ?, titolo = ?, tematica = ?, tipologia = ? WHERE id_doc= ? ";
            PreparedStatement preparedStatement = connection.prepareStatement(updateTableSQL);
              //  System.out.println(titolo);
            preparedStatement.setString(1,link);
              // System.out.println(link);
            preparedStatement.setString(2,titolo);
              // System.out.println(tematicaUpdate);
            preparedStatement.setString(3,tematicaUpdate);
              // System.out.println(tipologiaUpdate);
            preparedStatement.setString(4,tipologiaUpdate);
              // System.out.println(dettaglio.getId());
            preparedStatement.setInt(5,dettaglio.getId());
            System.out.println("Righe Update: "+preparedStatement.executeUpdate());

       }else if(dettPres==false){
            String updateTableSQL = "INSERT INTO dettaglio (id_doc,link,titolo,tematica,tipologia) VALUES(?,?,?,?,?)";
            PreparedStatement preparedStatement2 = connection.prepareStatement(updateTableSQL);
            preparedStatement2.setInt(1,documento.getId());
            //  System.out.println(titolo);
            preparedStatement2.setString(2,link);
              // System.out.println(link);
            preparedStatement2.setString(3,titolo);
              // System.out.println(tematicaUpdate);
            preparedStatement2.setString(4,tematicaUpdate);
              // System.out.println(tipologiaUpdate);
            preparedStatement2.setString(5,tipologiaUpdate);
              // System.out.println(dettaglio.getId());
            preparedStatement2.setInt(6,dettaglio.getId());
             System.out.println("Righe Insert: "+preparedStatement2.executeUpdate());
       }

           
            
            
         
       
       }catch(SQLException ex){
           ex.printStackTrace();
       }
*/
    }//GEN-LAST:event_ModificaActionPerformed

    private void ThemeSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemeSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThemeSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
       
        /* Create and display the form */
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AuthorText;
    private javax.swing.JList<String> CommentList;
    private javax.swing.JTextField KeyWordText;
    private javax.swing.JLabel Link;
    private javax.swing.JTextField LinkText;
    private javax.swing.JButton Modifica;
    private javax.swing.JTextField PersonalTagText;
    private javax.swing.JComboBox<String> ThemeSelect;
    private javax.swing.JTextField TitleText;
    private javax.swing.JComboBox<String> TypologySelect;
    private com.toedter.calendar.JDateChooser dataReadCalendar;
    private javax.swing.JLabel filenameLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider rateSlider;
    private javax.swing.JLabel stateLabel;
    // End of variables declaration//GEN-END:variables
}
