/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Donatella Malta
 */
package insert;

import Bibliography.MyConnection;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JComponent;
import java.io.File;
import java.sql.DriverManager;
import javax.swing.JTextField;
import java.sql.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;

public class Insert extends javax.swing.JFrame {

    private static Connection conn;
    private static MyConnection myConn;
    private static Statement stm;

    public Insert(MyConnection myConn) {
        
        this.myConn = myConn;
        try {
            conn = myConn.getConnection();
            conn.setAutoCommit(false);  //avvio la transazione appena apro la finestra
            stm = conn.createStatement();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
        initComponents();

        try {
            dropDownMenuSubject();
            dropDownMenuType();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (NullPointerException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        selectFile = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        detailLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        linkLabel = new javax.swing.JLabel();
        tagLabel = new javax.swing.JLabel();
        keywordLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        subjectLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        authorField = new javax.swing.JTextField();
        linkField = new javax.swing.JTextField();
        tagField = new javax.swing.JTextField();
        keywordField = new javax.swing.JTextField();
        typeCombo = new javax.swing.JComboBox<>();
        subjectCombo = new javax.swing.JComboBox<>();
        addTypeButton = new javax.swing.JButton();
        addSubjectButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        infoAuthorLabel = new javax.swing.JLabel();
        infoTagLabel = new javax.swing.JLabel();
        infoKeywordLabel = new javax.swing.JLabel();
        fileNameText = new javax.swing.JTextField();
        readCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectFile.setText("Scegli file");
        selectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileActionPerformed(evt);
            }
        });

        detailLabel.setText("DETTAGLI");

        titleLabel.setText("Titolo");

        authorLabel.setText("Autore");

        linkLabel.setText("Link");

        tagLabel.setText("Tag personale");

        keywordLabel.setText("Parola chiave");

        typeLabel.setText("Tipologia");

        subjectLabel.setText("Tematica");

        titleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleFieldActionPerformed(evt);
            }
        });

        authorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorFieldActionPerformed(evt);
            }
        });

        linkField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkFieldActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, linkLabel, org.jdesktop.beansbinding.ObjectProperty.create(), typeCombo, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);

        typeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboActionPerformed(evt);
            }
        });

        subjectCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectComboActionPerformed(evt);
            }
        });

        addTypeButton.setText("Aggiungi nuova");
        addTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTypeButtonActionPerformed(evt);
            }
        });

        addSubjectButton.setText("Aggiungi nuova");
        addSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectButtonActionPerformed(evt);
            }
        });

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        infoAuthorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insert/12575cb9a51ad34.jpg"))); // NOI18N
        infoAuthorLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                infoAuthorLabelMouseMoved(evt);
            }
        });

        infoTagLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insert/12575cb9a51ad34.jpg"))); // NOI18N
        infoTagLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                infoTagLabelMouseMoved(evt);
            }
        });

        infoKeywordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insert/12575cb9a51ad34.jpg"))); // NOI18N
        infoKeywordLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                infoKeywordLabelMouseMoved(evt);
            }
        });

        fileNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameTextActionPerformed(evt);
            }
        });

        readCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        readCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Letto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailLabel)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(typeLabel)
                            .addComponent(keywordLabel)
                            .addComponent(tagLabel)
                            .addComponent(linkLabel)
                            .addComponent(authorLabel)
                            .addComponent(titleLabel))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keywordField)
                            .addComponent(linkField)
                            .addComponent(tagField)
                            .addComponent(titleField)
                            .addComponent(typeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authorField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subjectLabel)
                            .addComponent(jLabel1))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(readCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(subjectCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoAuthorLabel)
                    .addComponent(infoTagLabel)
                    .addComponent(infoKeywordLabel))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(196, 196, 196))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addSubjectButton)
                            .addComponent(addTypeButton))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fileNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectFile)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFile)
                    .addComponent(fileNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infoAuthorLabel)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linkLabel)
                    .addComponent(linkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tagField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infoTagLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keywordLabel)
                    .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoKeywordLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeLabel)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subjectLabel)
                    .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(32, 32, 32))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileActionPerformed
        // TODO add your handling code here:

        JFileChooser fileChooser = new JFileChooser();
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            try {
                String fileName = fileChooser.getSelectedFile().getName();
                fileNameText.setText(fileName);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_selectFileActionPerformed

    private void typeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboActionPerformed

    private void titleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldActionPerformed

    private void authorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorFieldActionPerformed

    private void linkFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkFieldActionPerformed

    private void addTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTypeButtonActionPerformed
        String newType = JOptionPane.showInputDialog(null, "Inserisci una nuova tipologia", "Aggiungi", JOptionPane.PLAIN_MESSAGE);
        
        try{
            insertType(newType);
            dropDownMenuTypeSelected(newType);
            
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }


    }//GEN-LAST:event_addTypeButtonActionPerformed

    private void addSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectButtonActionPerformed
        
        String newSubject = JOptionPane.showInputDialog(null, "Inserisci una nuova tematica", "Aggiungi", JOptionPane.PLAIN_MESSAGE);
        
        try{
            insertSubject(newSubject);
            dropDownMenuSubjectSelected(newSubject);
            
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_addSubjectButtonActionPerformed

    public void insertSubject(String subject)throws SQLException{
        String query_insert_subject = "INSERT INTO tematica (nome) VALUES (?);";
        PreparedStatement stmtSub = conn.prepareStatement(query_insert_subject);
        stmtSub.setString(1, subject);
        stmtSub.executeUpdate();
    
    }
    public void insertType(String subject)throws SQLException{
        String query_insert_type = "INSERT INTO tipologia (nome) VALUES (?);";
        PreparedStatement stmtTyp = conn.prepareStatement(query_insert_type);
        stmtTyp.setString(1, subject);
        stmtTyp.executeUpdate();
    
    }
    
    
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        /*FORM READING*/
        /*Scorre il testo del campo, se trova il punto mette la parola letta in un array*/
        String fileName = "";
        String extension = "";
        
        String file = fileNameText.getText();
        if (!isEmpty(file)) {
            file = file.replace("\'", "\\'");
            String[] fileTokens = file.split("\\."); //divide la stringa in base a questa regex
            if (fileTokens.length > 2) { //se ci sono più punti, prendo solo l'ultimo elemento dell'array.
                for (int i = 0; i < fileTokens.length - 1; i++) {
                    fileName = fileName + fileTokens[i];
                }
                extension = fileTokens[fileTokens.length - 1];
            } else {
                fileName = fileTokens[0];
                extension = fileTokens[1];
            }
        }

        /*Read title and link*/
        String title = titleField.getText();
        String link = linkField.getText();

        /*Read Authors*/
        String authorText = authorField.getText();
        String[] authors = getAuthorText(authorText);
        
        /*Read tags*/
        String tagText = tagField.getText();
        String[] tags = getTagText(tagText);

        /*Read keywords*/
        String keywordText = keywordField.getText();
        String[] keywords = getKeywordText(keywordText);

        /*Read typology, subject and read/don't read field*/
        String typeString = typeCombo.getSelectedItem().toString();
        String subjectString = subjectCombo.getSelectedItem().toString();
        String readString = readCombo.getSelectedItem().toString();
        
        boolean read;
        if (readString.equals("Si")) {
            read = true;
        } else {
            read = false;
        }

        /*DATABASE ACCESS*/
        try {
            if (file.equals("")) {
                try {
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Non è stato inserito alcun documento!", "error", JOptionPane.ERROR_MESSAGE);
                    conn.rollback(); //se non ho inserito nessun documento devo annullare tutte le modifiche
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            } else {
                insertDocument(fileName, extension, read);
                int idDoc = selectIDDoc(fileName, extension);
                insertDetail(idDoc, link, title, subjectString, typeString); //TODO INSERIRE AUTORE
                
                if(!authorText.equals("")){
                    insertAuthors(authors);
                    insertCreation(idDoc, authors);
                }
                if (!tagText.equals("")){
                    insertTags(tags);
                    insertMark(idDoc, tags);
                }
                if (!keywordText.equals("")){
                   insertKeywors(keywords);
                    insertIdentification(idDoc, keywords);
                }
                conn.commit(); //fine transazione
                JOptionPane.showMessageDialog(null, "Operazione avvenuta correttamente", "Information", JOptionPane.INFORMATION_MESSAGE);
                clearField();
            }
            
        } catch (SQLException e) {
            System.err.println("Error:" + e.toString());
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    public String[] getAuthorText(String authorText){
        String[] authorTokens = authorText.split(","); //divide la stringa in base a questa regex
        for (int i = 0; i < authorTokens.length; i++) {
            authorTokens[i] = authorTokens[i].trim();
        }
        return authorTokens;
    }
    public String[] getTagText(String tagText){
        String[] tagTokens = tagText.split(","); //divide la stringa in base a questa regex
        for (int i = 0; i < tagTokens.length; i++) {
            tagTokens[i] = tagTokens[i].trim();
        }
        return tagTokens;
    }
    public String[] getKeywordText (String keywordText){
            String[] keywordTokens = keywordText.split(","); //divide la stringa in base a questa regex
            for (int i = 0; i < keywordTokens.length; i++) {
                keywordTokens[i] = keywordTokens[i].trim();
            }
            return keywordTokens;
    }
    
    public void dropDownMenuSubject() throws SQLException {
        ResultSet subjects = stm.executeQuery("SELECT nome FROM tematica");
        if (subjects.wasNull()) {
            System.out.println("Non ci sono tematiche presenti");
        } else {
            DefaultComboBoxModel cbModel1 = new DefaultComboBoxModel();
            cbModel1.addElement("");
            while (subjects.next()) {
                cbModel1.addElement(subjects.getString("nome"));
                subjectCombo.setModel(cbModel1);
            }
        }
    }
    public void dropDownMenuSubjectSelected(String subject) throws SQLException {
        ResultSet subjects = stm.executeQuery("SELECT nome FROM tematica");
        if (subjects.wasNull()) {
            System.out.println("Non ci sono tematiche presenti");
        } else {
            DefaultComboBoxModel cbModel1 = new DefaultComboBoxModel();
            cbModel1.addElement(subject);
            while (subjects.next()) {
                cbModel1.addElement(subjects.getString("nome"));
                subjectCombo.setModel(cbModel1);
            }
        }
    }

    public void dropDownMenuType() throws SQLException {
        ResultSet types = stm.executeQuery("SELECT nome FROM tipologia");
        if (types.wasNull()) {
            System.out.println("Non ci sono tipologie presenti");
        } else {
            DefaultComboBoxModel cbModel2 = new DefaultComboBoxModel();
            cbModel2.addElement("");
            while (types.next()) {
                cbModel2.addElement(types.getString("nome"));
                typeCombo.setModel(cbModel2);
            }
        }
    }
    public void dropDownMenuTypeSelected(String type) throws SQLException {
        ResultSet types = stm.executeQuery("SELECT nome FROM tipologia");
        if (types.wasNull()) {
            System.out.println("Non ci sono tipologie presenti");
        } else {
            DefaultComboBoxModel cbModel2 = new DefaultComboBoxModel();
            cbModel2.addElement(type);
            while (types.next()) {
                cbModel2.addElement(types.getString("nome"));
                typeCombo.setModel(cbModel2);
            }
        }
    }

    public void insertDocument(String fileName, String extension, boolean read) throws SQLException {
        String query_insert_document="";
        PreparedStatement stmtDoc;
        if(read==true){
            query_insert_document = "INSERT INTO documento (nome_file, estensione, data_inserimento, data_lettura, stato) VALUES (?, ?, NOW(), NOW(), ?);";
        }else{
            query_insert_document = "INSERT INTO documento (nome_file, estensione, data_inserimento, stato) VALUES (?, ?, NOW(), ?);";
        }
        stmtDoc= conn.prepareStatement(query_insert_document);
        stmtDoc.setString(1, fileName);
        stmtDoc.setString(2, extension);
        stmtDoc.setBoolean(3, read);
        stmtDoc.executeUpdate();
    }
    
    public int selectIDDoc(String fileName, String extension) throws SQLException {
        int idDoc = 0;
        PreparedStatement stmID;
        String query_acquire_IdDoc = "SELECT id FROM documento WHERE nome_file = ? and estensione = ?";
        stmID = conn.prepareStatement(query_acquire_IdDoc);
        stmID.setString(1, fileName);
        stmID.setString(2, extension);
        ResultSet rsID =  stmID.executeQuery();
        rsID.next();
        return rsID.getInt("id");
        
    }
    
    public void insertDetail(int idDoc, String link, String title, String subjectString, String typeString) throws SQLException {
        String query_insert_detail;
        if((subjectString.equals("")) && (typeString.equals(""))){
            query_insert_detail = "INSERT INTO dettaglio (id_doc, link, titolo) VALUES (?,?,?);";
            PreparedStatement stmtDet = conn.prepareStatement(query_insert_detail);
            stmtDet.setInt(1, idDoc);
            stmtDet.setString(2, link);
            stmtDet.setString(3, title);
            stmtDet.executeUpdate();
        }else if(subjectString.equals("")){
            query_insert_detail = "INSERT INTO dettaglio (id_doc, link, titolo, tipologia) VALUES (?,?,?,?);";
            System.out.println(query_insert_detail);
            PreparedStatement stmtDet = conn.prepareStatement(query_insert_detail);
            stmtDet.setInt(1, idDoc);
            stmtDet.setString(2, link);
            stmtDet.setString(3, title);
            stmtDet.setString(4, typeString);
            stmtDet.executeUpdate();
        }else if(typeString.equals("")){
            query_insert_detail = "INSERT INTO dettaglio (id_doc, link, titolo, tematica) VALUES (?,?,?,?);";
            PreparedStatement stmtDet = conn.prepareStatement(query_insert_detail);
            
            stmtDet.setInt(1, idDoc);
            stmtDet.setString(2, link);
            stmtDet.setString(3, title);
            stmtDet.setString(4, subjectString);
            
            System.out.println(query_insert_detail);
            stmtDet.executeUpdate();
        }else{
            query_insert_detail = "INSERT INTO dettaglio (id_doc, link, titolo, tematica, tipologia) VALUES (?,?,?,?,?);";
            PreparedStatement stmtDet = conn.prepareStatement(query_insert_detail);
            
            stmtDet.setInt(1, idDoc);
            stmtDet.setString(2, link);
            stmtDet.setString(3, title);
            stmtDet.setString(4, subjectString);
            stmtDet.setString(5, typeString);
            
            System.out.println(query_insert_detail);
            stmtDet.executeUpdate();
        }
    }

    public void insertAuthors(String[] authors)throws SQLException{
        //controllo prima se non sono presenti autori con lo stesso nome
        for(int i=0; i<authors.length; i++){
            String query_check_author = "SELECT count(*) FROM autore WHERE nome = ? ";
            PreparedStatement stmtCheckAuth = conn.prepareStatement(query_check_author);
            stmtCheckAuth.setString(1, authors[i]);
            ResultSet rst = stmtCheckAuth.executeQuery();
            int authorIn =0;
            while(rst.next()){
                authorIn = rst.getInt("count");
            }
            if(authorIn==0){
                String query_insert_author = "INSERT INTO autore (nome) VALUES (?);";
                PreparedStatement stmtAuth = conn.prepareStatement(query_insert_author);
                stmtAuth.setString(1, authors[i]);
                stmtAuth.executeUpdate();
            }
        }
    }
    public void insertCreation (int idDoc, String[] authors) throws SQLException{
        for(int i=0; i<authors.length; i++){
            System.out.println("Id_doc "+idDoc);
            String query_insert_creation = "INSERT INTO creazione (dettaglio, autore) VALUES (?,?);";
            PreparedStatement stmtCr = conn.prepareStatement(query_insert_creation);
            stmtCr.setInt(1, idDoc);
            stmtCr.setString(2, authors[i]);
            stmtCr.executeUpdate();
            System.out.println(stmtCr);
        }
    }
    
    public void insertTags(String[] tags)throws SQLException{
        for(int i=0; i<tags.length; i++){
            String query_insert_tags = "INSERT INTO tagpersonale (parola) VALUES (?);";
            PreparedStatement stmtAuth = conn.prepareStatement(query_insert_tags);
            stmtAuth.setString(1, tags[i]);
            stmtAuth.executeUpdate();
        }
    }
    public void insertMark(int idDoc, String[] tags) throws SQLException{
        for(int i=0; i<tags.length; i++){
            System.out.println("Id_doc "+idDoc);
            String query_insert_mark = "INSERT INTO contrassegno (dettaglio, tag_personale) VALUES (?,?);";
            PreparedStatement stmtCr = conn.prepareStatement(query_insert_mark);
            stmtCr.setInt(1, idDoc);
            stmtCr.setString(2, tags[i]);
            stmtCr.executeUpdate();
            System.out.println(stmtCr);
        }
    }
    
    public void insertKeywors(String[] keywords)throws SQLException{
        for(int i=0; i<keywords.length; i++){
            String query_insert_keywords = "INSERT INTO parolachiave (parola) VALUES (?);";
            PreparedStatement stmtAuth = conn.prepareStatement(query_insert_keywords);
            stmtAuth.setString(1, keywords[i]);
            stmtAuth.executeUpdate();
        }
    }
    public void insertIdentification(int idDoc, String[] keywords) throws SQLException{
        for(int i=0; i<keywords.length; i++){
            System.out.println("Id_doc "+idDoc);
            String query_insert_mark = "INSERT INTO individuazione (dettaglio, parola_chiave) VALUES (?,?);";
            PreparedStatement stmtCr = conn.prepareStatement(query_insert_mark);
            stmtCr.setInt(1, idDoc);
            stmtCr.setString(2, keywords[i]);
            stmtCr.executeUpdate();
            System.out.println(stmtCr);
        }
    }
    
    public void clearField() throws SQLException{
        fileNameText.setText(null);
        titleField.setText(null);
        linkField.setText(null);
        authorField.setText(null);
        tagField.setText(null);
        keywordField.setText(null);
        dropDownMenuSubject();
        dropDownMenuType();
        
        
    }
    private void infoAuthorLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoAuthorLabelMouseMoved
        try {
            infoAuthorLabel.setToolTipText("Puoi inserire più autori, purchè siano separati da una virgola.");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_infoAuthorLabelMouseMoved

    private void infoTagLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoTagLabelMouseMoved
        try {
            infoTagLabel.setToolTipText("Puoi inserire più tag, purchè siano separati da una virgola.");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_infoTagLabelMouseMoved

    private void infoKeywordLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoKeywordLabelMouseMoved
        try {
            infoKeywordLabel.setToolTipText("Puoi inserire più parole chiave, purchè siano separate da una virgola.");
            System.out.println("Info");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_infoKeywordLabelMouseMoved

    private void fileNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameTextActionPerformed

    private void readComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readComboActionPerformed

    private void subjectComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert(myConn).setVisible(true);
            }
        });
    }

    /*Restituisce vero se la stringa è vuota*/
    private boolean isEmpty(String text) {
        return text.equals("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectButton;
    private javax.swing.JButton addTypeButton;
    private javax.swing.JTextField authorField;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JTextField fileNameText;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel infoAuthorLabel;
    private javax.swing.JLabel infoKeywordLabel;
    private javax.swing.JLabel infoTagLabel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField keywordField;
    private javax.swing.JLabel keywordLabel;
    private javax.swing.JTextField linkField;
    private javax.swing.JLabel linkLabel;
    private javax.swing.JComboBox<String> readCombo;
    private javax.swing.JButton selectFile;
    private javax.swing.JComboBox<String> subjectCombo;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField tagField;
    private javax.swing.JLabel tagLabel;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> typeCombo;
    private javax.swing.JLabel typeLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
